Repository hmcts/div-fees-and-payments-service, pull requests merged in 2019-06, with the labels that each got.

#55 Set instance size to I3
  infrastructure/main.tf
Labels: ns:div-fps-pr-55

#56 Adjust instance size by variable
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-fps-pr-56

#54 DIV-4484 upgrade gradle version to 5.x
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:div-fps-pr-54

#57 DIV-5060: OWASP upgrade and checkstyle added to build
  build.gradle
  checkstyle.xml
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactory.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheck.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactoryUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheckUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
Labels: ns:div-fps-pr-57
