Repository hmcts/div-fees-and-payments-service, pull requests merged in 2019-01, with the labels that each got.

#36 Move to shared ASP 1
  infrastructure/main.tf
Labels: ns:div-fps-pr-36

#38 DIV-3885 - added fees service health check
  infrastructure/main.tf
  infrastructure/variables.tf
  src/kubernetes/config.aat.yaml
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/FeesAndPaymentsServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
  src/test/resources/application.yml
Labels: ns:div-fps-pr-38

#37 Revert to normal ASP and use larger instance size
  infrastructure/main.tf
Labels: ns:div-fps-pr-37

#39 [PREVIEW] DIV-3814 - removed dependency check suppression for CVE-2018-8088
  dependency-check-suppressions.xml
Labels: ns:div-fps-pr-39
