Repository hmcts/div-fees-and-payments-service, pull requests merged in 2019-05, with the labels that each got.

#49 Enable notifications on master only
  Jenkinsfile_CNP
Labels: ns:div-fps-pr-49

#50 Fix tomcat CVE
  build.gradle
Labels: ns:div-fps-pr-50

#52 Override Spring's management endpoint cache to 30 seconds in AAT/Preview
  build.gradle
  charts/div-fps/values.aat.template.yaml
  charts/div-fps/values.preview.template.yaml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
Labels: ns:div-fps-pr-52

#53 Fixed invalid tf attribute - value -> default
  infrastructure/variables.tf
Labels: ns:div-fps-pr-53

#51 DIV-4835 Fix PMD/checkstyle warnings
  ruleset.xml
Labels: ns:div-fps-pr-51
