Repository hmcts/div-fees-and-payments-service, pull requests merged in 2019-09, with the labels that each got.

#63 DIV-5520 aks migration
  Dockerfile
  Jenkinsfile_CNP
  build.gradle
  charts/div-fps/Chart.yaml
  charts/div-fps/requirements.yaml
  charts/div-fps/values.aat.template.yaml
  charts/div-fps/values.preview.template.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.3.1.jar
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/insights/AppInsights.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/insights/AppInsightsTest.java
  web.config
Labels: ns:div-fps-pr-63

#65 Use hmcts/cnp module
  infrastructure/main.tf
Labels: ns:div-fps-pr-65

#66 DIV-5762 - use java chart v2.6.0 and reduced duplicated env references
  charts/div-fps/Chart.yaml
  charts/div-fps/requirements.yaml
  charts/div-fps/values.aat.template.yaml
  charts/div-fps/values.preview.template.yaml
  charts/div-fps/values.yaml
Labels: ns:div-fps-pr-66

#70 DIV-5781: Address Jackson Databind vulnerabilities (CVE-2019-14540 and 16335)
  dependency-check-suppressions.xml
Labels: ns:div-fps-pr-70

#69 Delete application from ASE
  infrastructure/main.tf
Labels: ns:div-fps-pr-69
