Repository hmcts/div-fees-and-payments-service, pull requests merged in 2019-10, with the labels that each got.

#71 cleanup ase
  Dockerfile
  dependency-check-suppressions.xml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  lib/applicationinsights-agent-2.3.1.jar
Labels: ns:div-fps-pr-71

#73 DIV-5844 - Update ithc
  Dockerfile
  Jenkinsfile_CNP
  build.gradle
  charts/div-fps/Chart.yaml
  charts/div-fps/requirements.yaml
  charts/div-fps/values.aat.template.yaml
  charts/div-fps/values.preview.template.yaml
  charts/div-fps/values.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  lib/AI-Agent.xml
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/insights/AppInsights.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/insights/AppInsightsTest.java
  web.config
Labels: ns:div-fps-pr-73

#74 Remove vuln suppressions & code cleanup as suggested by PMD
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceController.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/helper/RestResponseEntityExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/management/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/model/Fee.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentService.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/RootControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
Labels: ns:div-fps-pr-74

#75 Add dependabot config
  .dependabot/config.yml
Labels: ns:div-fps-pr-75

#86 Bump health starter
  build.gradle
Labels: ns:div-fps-pr-86
