Repository hmcts/div-fees-and-payments-service, pull requests merged in 2020-02, with the labels that each got.

#124 Cleaned up code
  README.md
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactory.java
  src/main/resources/banner.txt
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactoryUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheckUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/feepayment/smoketest/SmokeTest.java
Labels: ns:divorce, rel:div-fps-pr-124

#125 RPET-58: Remove the deprecated enableDockerBuild() configuration
  Jenkinsfile_CNP
Labels: ns:divorce, rel:div-fps-pr-125

#126 fix owasp check style issue
  build.gradle
  checkstyle.xml
Labels: ns:divorce, rel:div-fps-pr-126

#127 fix owasp security issue
  build.gradle
Labels: ns:divorce, rel:div-fps-pr-127
