Repository hmcts/div-fees-and-payments-service, pull requests merged in 2020-01, with the labels that each got.

#107 Zap security python compatibility
  security.sh
Labels: ns:div-fps-pr-107

#109 fix owasp dependency check issue
  build.gradle
Labels: ns:divorce, rel:div-fps-pr-109

#110 add report json file
  security.sh
Labels: ns:divorce, rel:div-fps-pr-110

#114 Tidied up Fees and Payments project & gradle
  build.gradle
  config.yml
  dependency-check-suppressions.xml
  ruleset.xml
  src/.lint.yml
Labels: ns:divorce, rel:div-fps-pr-114

#123 FIX-Address CVE-2020-5398 and upgrade dependencies + fix deprecated code
  .dependabot/config.yml
  build.gradle
  src/main/java/uk/gov/hmcts/reform/divorce/feepayment/config/HttpConnectionConfiguration.java
Labels: ns:divorce, rel:div-fps-pr-123
