Repository hmcts/div-fees-and-payments-service, pull requests merged in 2021-03, with the labels that each got.

#213 Update Tomcat due to CVE
  build.gradle
Labels: ns:divorce, prd:div, rel:div-fps-pr-213

#214 dependencies improvements
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-fps-pr-214

#222 Fix azure logging
  charts/div-fps/Chart.yaml
  charts/div-fps/values.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  src/main/resources/bootstrap.yaml
Labels: ns:divorce, prd:div, rel:div-fps-pr-222
