Repository hmcts/div-fees-and-payments-service, pull requests merged in 2022-05, with the labels that each got.

#317 Autoscaling
  charts/div-fps/Chart.yaml
  charts/div-fps/values.yaml
Labels: ns:divorce, prd:div, rel:div-fps-pr-317

#318 Bumping tomcat
  build.gradle
Labels: ns:divorce, prd:div, rel:div-fps-pr-318

#322 Bumping springframework
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-fps-pr-322
