Repository hmcts/div-fees-and-payments-service, pull requests merged in 2022-08, with the labels that each got.

#335 DFR-1086 Update Readme
  README.md
Labels: ns:divorce, prd:div, rel:div-fps-pr-335

#336 Add backstage configuration file
  catalog-info.yaml
Labels: ns:divorce, prd:div, rel:div-fps-pr-336

#338 Fix Functional tests
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java
  src/integrationTest/resources/application.properties
Labels: ns:divorce, prd:div, rel:div-fps-pr-338
